export {default as Actors} from "./Actors/Aktors"
export {default as MovieInformation} from "./MovieInformation/MovieInformation"
export {default as Movies} from "./Movies/Movies"
export {default as Navbar} from "./Navbar/Navbar"
export {default as Profile} from "./Profile/Profile"
